//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class MDOLEntities1 : DbContext
{
    public MDOLEntities1()
        : base("name=MDOLEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Age> Ages { get; set; }
    public DbSet<Animal> Animals { get; set; }
    public DbSet<AnimalRequirement> AnimalRequirements { get; set; }
    public DbSet<Country> Countries { get; set; }
    public DbSet<County> Counties { get; set; }
    public DbSet<Gender> Genders { get; set; }
    public DbSet<Origin> Origins { get; set; }
    public DbSet<Requirement> Requirements { get; set; }
    public DbSet<RequirementType> RequirementTypes { get; set; }
    public DbSet<Species> Species { get; set; }
    public DbSet<State> States { get; set; }
    public DbSet<Type> Types { get; set; }
    public DbSet<Vaccination> Vaccinations { get; set; }
}
